package testPackage1;// Generated by Selenium IDE

import org.junit.*;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.seleniumhq.jetty9.util.log.Log;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WikiTest1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:\\chromedriver.exe");

        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void wikiTest1() {
        driver.get("https://www.google.com/");
        driver.manage().window().setSize(new Dimension(1050, 708));
        driver.findElement(By.name("q")).sendKeys(Keys.DOWN);
        driver.findElement(By.name("q")).sendKeys("wikipedia");
        driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".LC20lb")).click();
        //driver.findElement(By.cssSelector(".g > div > div > .rc .LC20lb")).click();
        driver.findElement(By.id("searchInput")).sendKeys("nightwish");
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        driver.findElement(By.id("searchInput")).sendKeys(Keys.DOWN); //почему пропускается?
        driver.findElement(By.id("searchInput")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("ul:nth-child(97) > li:nth-child(9) > i > a")).click();
        driver.findElement(By.id("Список_композиций")).click();
        //assertThat(driver.findElement(By.id("Список_композиций")).getText(), is("Список композиций"));
        String actual = driver.findElement(By.id("Список_композиций")).getText();
        String expected = "Список композиций";
        Assert.assertEquals(expected, actual);
    }
}
