package testPackage1;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WikipediaTest1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;


    @Before
    public void setUp() {

        //1111
        System.setProperty("webdriver.gecko.driver", "C:\\GeckoDriver.exe");
        DesiredCapabilities capabilities = DesiredCapabilities.firefox();
        capabilities.setCapability("marionette", true);
        //1111

        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }


    @Test
    public void wikipediaTest1() {
        driver.get("https://www.wikipedia.org/");
        driver.manage().window().setSize(new Dimension(1382, 744));
        driver.findElement(By.cssSelector(".other-project:nth-child(8) .other-project-title")).click();
        driver.findElement(By.linkText("Wikipedia")).click();
        driver.findElement(By.id("searchLanguage")).click();
        {
            WebElement dropdown = driver.findElement(By.id("searchLanguage"));
            dropdown.findElement(By.xpath("//option[. = 'English']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(12)")).click();
        driver.findElement(By.id("searchInput")).click();
        driver.findElement(By.id("searchInput")).sendKeys("Nightwish");
        driver.findElement(By.id("searchInput")).sendKeys(Keys.DOWN);
        driver.findElement(By.id("searchInput")).sendKeys(Keys.ENTER);
        js.executeScript("window.scrollTo(0,10612)"); //а вот тут мы падаем по ходу...
        driver.findElement(By.linkText("Human. :II: Nature. World Tour")).click();
        driver.findElement(By.linkText("Beast in Black")).click();
    }
}
